version: '3.8'

services:
  pentaforge:
    image: pentaforge:latest
    container_name: pentaforge-mcp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - TZ=${TZ:-UTC}
      - LANG=${LANG:-en_US.UTF-8}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PENTAFORGE_OUTPUT_DIR=${PENTAFORGE_OUTPUT_DIR:-/app/PRPs/inputs}
    volumes:
      # Map host directory to container for output persistence
      - ./PRPs/inputs:/app/PRPs/inputs
    stdin_open: true
    tty: false
    # For better security, run as non-root user (already configured in Dockerfile)
    # Optionally override with host user ID on Linux:
    # user: "${UID:-1001}:${GID:-1001}"
    restart: "no"
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M